### ISSUE TITLE
网络监控栏不显示，切换官方默认主题能显示

### ISSUE THREAD

**Issue by loohalh** [kshipeng/nezhaThemeCustom#1]
官方主题会有个网络监控，大佬的主题不显示网络监控栏
<img width="958" alt="image" src="https://github.com/kshipeng/nezhaThemeCustom/assets/16890588/bc977419-3c14-411c-9dc7-0b6a2702ff6d">

**Comment by kshipeng** [comment]
适配了0.16.2版的哪吒。修改`menu.html`文件，新增`network.html`文件，然后重启哪吒面板即可

**Comment by loohalh** [comment]
> 适配了0.16.2版的哪吒。修改`menu.html`文件，新增`network.html`文件，然后重启哪吒面板即可

已经OK了 👍
